---
- name: Clone git repository
  become: true
  become_user: "{{ pbin_user }}"
  git:
    repo: "{{ pbin_git_repo }}"
    dest: "{{ pbin_path }}"
    version: "{{ pbin_git_version }}"

- name: Template conf.php
  template:
    src: conf.php.j2
    dest: "{{ pbin_path }}/cfg/conf.php"
    owner: "{{ pbin_user }}"
    group: "{{ pbin_group }}"
    mode: "0644"
